export type EmotionTag =
  | "Fear"
  | "FOMO"
  | "Revenge"
  | "Hesitation"
  | "Greed"
  | "Confidence"
  | "Tilt"
  | "Impulsive"
  | "Disciplined";

export type Session = "Open" | "Midday" | "Power Hour";
export type MarketRegime = "Trend Up" | "Trend Down" | "Chop" | "Volatile";
export type AssetType = "Equity" | "Futures" | "Crypto" | "Options";

export interface Trade {
  id: string;
  ticker: string;
  assetType: AssetType;
  side: "Long" | "Short";
  setup: string;
  entryPrice: number;
  exitPrice: number;
  positionSize: number;
  pnl: number;
  riskPercent: number;
  plannedRisk: number;
  actualRisk: number;
  rMultiple: number;
  durationMinutes: number;
  date: string;
  time: string;
  session: Session;
  marketRegime: MarketRegime;
  volumeRegime: "High" | "Normal" | "Low";
  emotionTags: EmotionTag[];
  notes: string;
  ruleAdherence: number;
  stopRespected: boolean;
  confidence: number;
  stress: number;
  sleep: number;
  focus: number;
  broker: string;
  isRevenge: boolean;
  isFomo: boolean;
}

export interface PsychologyLog {
  date: string;
  confidence: number;
  stress: number;
  sleep: number;
  focus: number;
  emotionalState: EmotionTag;
  distractions: number;
  journal: string;
}

const recentSampleTrades: Trade[] = [
  {
    id: "TR-1001",
    ticker: "NVDA",
    assetType: "Equity",
    side: "Long",
    setup: "Opening Range Breakout",
    entryPrice: 113.2,
    exitPrice: 116.8,
    positionSize: 180,
    pnl: 648,
    riskPercent: 2.2,
    plannedRisk: 420,
    actualRisk: 410,
    rMultiple: 1.54,
    durationMinutes: 42,
    date: "2026-04-20",
    time: "09:42",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined", "Confidence"],
    notes: "Waited for volume confirmation and took partials at 1R.",
    ruleAdherence: 94,
    stopRespected: true,
    confidence: 7,
    stress: 3,
    sleep: 7,
    focus: 8,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1002",
    ticker: "AAPL",
    assetType: "Options",
    side: "Long",
    setup: "VWAP Bounce",
    entryPrice: 2.15,
    exitPrice: 1.52,
    positionSize: 8,
    pnl: -504,
    riskPercent: 3.8,
    plannedRisk: 320,
    actualRisk: 520,
    rMultiple: -1.58,
    durationMinutes: 93,
    date: "2026-04-20",
    time: "12:26",
    session: "Midday",
    marketRegime: "Chop",
    volumeRegime: "Low",
    emotionTags: ["FOMO", "Impulsive"],
    notes: "Entered late after missing the first clean bounce.",
    ruleAdherence: 42,
    stopRespected: false,
    confidence: 9,
    stress: 7,
    sleep: 7,
    focus: 5,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: true
  },
  {
    id: "TR-1003",
    ticker: "ES",
    assetType: "Futures",
    side: "Short",
    setup: "Trend Continuation",
    entryPrice: 5198.5,
    exitPrice: 5189.25,
    positionSize: 2,
    pnl: 925,
    riskPercent: 2.6,
    plannedRisk: 600,
    actualRisk: 610,
    rMultiple: 1.52,
    durationMinutes: 34,
    date: "2026-04-21",
    time: "10:14",
    session: "Open",
    marketRegime: "Trend Down",
    volumeRegime: "High",
    emotionTags: ["Disciplined"],
    notes: "Clean pullback into prior support. Exited into liquidity sweep.",
    ruleAdherence: 91,
    stopRespected: true,
    confidence: 6,
    stress: 4,
    sleep: 8,
    focus: 8,
    broker: "Tradovate",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1004",
    ticker: "TSLA",
    assetType: "Equity",
    side: "Long",
    setup: "Breakout",
    entryPrice: 184.6,
    exitPrice: 181.7,
    positionSize: 160,
    pnl: -464,
    riskPercent: 3.6,
    plannedRisk: 330,
    actualRisk: 475,
    rMultiple: -1.41,
    durationMinutes: 77,
    date: "2026-04-21",
    time: "14:18",
    session: "Power Hour",
    marketRegime: "Volatile",
    volumeRegime: "Normal",
    emotionTags: ["Greed", "Tilt"],
    notes: "Moved stop twice after rejection candle.",
    ruleAdherence: 38,
    stopRespected: false,
    confidence: 8,
    stress: 8,
    sleep: 8,
    focus: 4,
    broker: "Robinhood",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1005",
    ticker: "NQ",
    assetType: "Futures",
    side: "Long",
    setup: "ORB",
    entryPrice: 18380.25,
    exitPrice: 18412.5,
    positionSize: 1,
    pnl: 645,
    riskPercent: 2.1,
    plannedRisk: 425,
    actualRisk: 400,
    rMultiple: 1.61,
    durationMinutes: 29,
    date: "2026-04-22",
    time: "09:48",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined", "Confidence"],
    notes: "Executed the playbook. No add after first target.",
    ruleAdherence: 96,
    stopRespected: true,
    confidence: 7,
    stress: 2,
    sleep: 8,
    focus: 9,
    broker: "Tradovate",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1006",
    ticker: "AMD",
    assetType: "Equity",
    side: "Short",
    setup: "Mean Reversion",
    entryPrice: 154.4,
    exitPrice: 156.25,
    positionSize: 260,
    pnl: -481,
    riskPercent: 4.2,
    plannedRisk: 350,
    actualRisk: 520,
    rMultiple: -1.37,
    durationMinutes: 118,
    date: "2026-04-22",
    time: "13:04",
    session: "Midday",
    marketRegime: "Trend Up",
    volumeRegime: "Normal",
    emotionTags: ["Hesitation", "Tilt"],
    notes: "Shorted strength without a failed retest.",
    ruleAdherence: 46,
    stopRespected: false,
    confidence: 5,
    stress: 8,
    sleep: 8,
    focus: 5,
    broker: "Webull",
    isRevenge: true,
    isFomo: false
  },
  {
    id: "TR-1007",
    ticker: "META",
    assetType: "Options",
    side: "Long",
    setup: "Trend Continuation",
    entryPrice: 4.4,
    exitPrice: 5.75,
    positionSize: 6,
    pnl: 810,
    riskPercent: 2.8,
    plannedRisk: 460,
    actualRisk: 450,
    rMultiple: 1.76,
    durationMinutes: 51,
    date: "2026-04-23",
    time: "10:32",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined"],
    notes: "Good patience after failed first candle.",
    ruleAdherence: 88,
    stopRespected: true,
    confidence: 6,
    stress: 4,
    sleep: 6,
    focus: 8,
    broker: "Interactive Brokers",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1008",
    ticker: "SPY",
    assetType: "Options",
    side: "Short",
    setup: "Scalp",
    entryPrice: 1.32,
    exitPrice: 1.06,
    positionSize: 12,
    pnl: 312,
    riskPercent: 1.6,
    plannedRisk: 260,
    actualRisk: 250,
    rMultiple: 1.2,
    durationMinutes: 17,
    date: "2026-04-23",
    time: "15:12",
    session: "Power Hour",
    marketRegime: "Chop",
    volumeRegime: "Normal",
    emotionTags: ["Confidence"],
    notes: "Small scalp after range rejection.",
    ruleAdherence: 78,
    stopRespected: true,
    confidence: 8,
    stress: 5,
    sleep: 6,
    focus: 7,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1009",
    ticker: "COIN",
    assetType: "Equity",
    side: "Long",
    setup: "Breakout",
    entryPrice: 248.1,
    exitPrice: 245.0,
    positionSize: 150,
    pnl: -465,
    riskPercent: 4.7,
    plannedRisk: 360,
    actualRisk: 510,
    rMultiple: -1.29,
    durationMinutes: 136,
    date: "2026-04-24",
    time: "11:56",
    session: "Midday",
    marketRegime: "Volatile",
    volumeRegime: "Low",
    emotionTags: ["FOMO", "Greed"],
    notes: "Chased the third push into resistance.",
    ruleAdherence: 35,
    stopRespected: false,
    confidence: 9,
    stress: 7,
    sleep: 5,
    focus: 4,
    broker: "Webull",
    isRevenge: false,
    isFomo: true
  },
  {
    id: "TR-1010",
    ticker: "NQ",
    assetType: "Futures",
    side: "Short",
    setup: "VWAP Reclaim Fail",
    entryPrice: 18448.75,
    exitPrice: 18465.25,
    positionSize: 1,
    pnl: -330,
    riskPercent: 3.5,
    plannedRisk: 260,
    actualRisk: 350,
    rMultiple: -1.27,
    durationMinutes: 89,
    date: "2026-04-24",
    time: "13:39",
    session: "Midday",
    marketRegime: "Trend Up",
    volumeRegime: "Normal",
    emotionTags: ["Revenge", "Tilt", "Impulsive"],
    notes: "Second trade after loss. Size was not reduced.",
    ruleAdherence: 28,
    stopRespected: false,
    confidence: 7,
    stress: 9,
    sleep: 5,
    focus: 3,
    broker: "Tradovate",
    isRevenge: true,
    isFomo: false
  },
  {
    id: "TR-1011",
    ticker: "MSFT",
    assetType: "Equity",
    side: "Long",
    setup: "VWAP Bounce",
    entryPrice: 414.2,
    exitPrice: 417.1,
    positionSize: 90,
    pnl: 261,
    riskPercent: 1.7,
    plannedRisk: 220,
    actualRisk: 215,
    rMultiple: 1.19,
    durationMinutes: 38,
    date: "2026-04-27",
    time: "10:08",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "Normal",
    emotionTags: ["Disciplined"],
    notes: "Smaller size helped hold to target.",
    ruleAdherence: 90,
    stopRespected: true,
    confidence: 6,
    stress: 3,
    sleep: 8,
    focus: 8,
    broker: "Interactive Brokers",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1012",
    ticker: "BTC",
    assetType: "Crypto",
    side: "Long",
    setup: "Breakout",
    entryPrice: 64220,
    exitPrice: 64840,
    positionSize: 0.8,
    pnl: 496,
    riskPercent: 2.5,
    plannedRisk: 330,
    actualRisk: 330,
    rMultiple: 1.5,
    durationMinutes: 64,
    date: "2026-04-27",
    time: "15:28",
    session: "Power Hour",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Confidence"],
    notes: "Took the daily range break with predefined stop.",
    ruleAdherence: 82,
    stopRespected: true,
    confidence: 8,
    stress: 4,
    sleep: 8,
    focus: 7,
    broker: "Binance",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1013",
    ticker: "AMZN",
    assetType: "Options",
    side: "Long",
    setup: "Opening Range Breakout",
    entryPrice: 3.75,
    exitPrice: 4.85,
    positionSize: 7,
    pnl: 770,
    riskPercent: 2.4,
    plannedRisk: 500,
    actualRisk: 490,
    rMultiple: 1.57,
    durationMinutes: 46,
    date: "2026-04-28",
    time: "09:51",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined", "Confidence"],
    notes: "Held partial runner after first target.",
    ruleAdherence: 93,
    stopRespected: true,
    confidence: 7,
    stress: 3,
    sleep: 7,
    focus: 8,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1014",
    ticker: "QQQ",
    assetType: "Options",
    side: "Short",
    setup: "Mean Reversion",
    entryPrice: 2.54,
    exitPrice: 2.91,
    positionSize: 10,
    pnl: -370,
    riskPercent: 3.3,
    plannedRisk: 280,
    actualRisk: 390,
    rMultiple: -1.32,
    durationMinutes: 111,
    date: "2026-04-28",
    time: "12:47",
    session: "Midday",
    marketRegime: "Trend Up",
    volumeRegime: "Low",
    emotionTags: ["Hesitation", "FOMO"],
    notes: "Counter-trend idea taken without confirmation.",
    ruleAdherence: 49,
    stopRespected: false,
    confidence: 6,
    stress: 7,
    sleep: 7,
    focus: 5,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: true
  },
  {
    id: "TR-1015",
    ticker: "ES",
    assetType: "Futures",
    side: "Long",
    setup: "Trend Continuation",
    entryPrice: 5228.25,
    exitPrice: 5235.5,
    positionSize: 2,
    pnl: 725,
    riskPercent: 2.0,
    plannedRisk: 480,
    actualRisk: 470,
    rMultiple: 1.51,
    durationMinutes: 27,
    date: "2026-04-29",
    time: "10:20",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined"],
    notes: "No hesitation, followed trend day rules.",
    ruleAdherence: 95,
    stopRespected: true,
    confidence: 6,
    stress: 2,
    sleep: 8,
    focus: 9,
    broker: "Tradovate",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1016",
    ticker: "NFLX",
    assetType: "Equity",
    side: "Short",
    setup: "Scalp",
    entryPrice: 591.1,
    exitPrice: 592.35,
    positionSize: 120,
    pnl: -150,
    riskPercent: 1.4,
    plannedRisk: 180,
    actualRisk: 170,
    rMultiple: -0.83,
    durationMinutes: 21,
    date: "2026-04-29",
    time: "14:34",
    session: "Power Hour",
    marketRegime: "Chop",
    volumeRegime: "Normal",
    emotionTags: ["Fear"],
    notes: "Cut quickly when the tape did not confirm.",
    ruleAdherence: 75,
    stopRespected: true,
    confidence: 4,
    stress: 5,
    sleep: 8,
    focus: 7,
    broker: "Interactive Brokers",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1017",
    ticker: "PLTR",
    assetType: "Equity",
    side: "Long",
    setup: "Breakout",
    entryPrice: 23.4,
    exitPrice: 22.2,
    positionSize: 520,
    pnl: -624,
    riskPercent: 5.1,
    plannedRisk: 360,
    actualRisk: 650,
    rMultiple: -1.73,
    durationMinutes: 154,
    date: "2026-05-01",
    time: "11:22",
    session: "Midday",
    marketRegime: "Chop",
    volumeRegime: "Low",
    emotionTags: ["FOMO", "Impulsive", "Tilt"],
    notes: "Oversized trade after watching it run without me.",
    ruleAdherence: 25,
    stopRespected: false,
    confidence: 9,
    stress: 8,
    sleep: 5,
    focus: 4,
    broker: "Robinhood",
    isRevenge: false,
    isFomo: true
  },
  {
    id: "TR-1018",
    ticker: "NQ",
    assetType: "Futures",
    side: "Long",
    setup: "VWAP Bounce",
    entryPrice: 18518.5,
    exitPrice: 18498.25,
    positionSize: 2,
    pnl: -810,
    riskPercent: 5.6,
    plannedRisk: 520,
    actualRisk: 840,
    rMultiple: -1.56,
    durationMinutes: 123,
    date: "2026-05-01",
    time: "13:16",
    session: "Midday",
    marketRegime: "Chop",
    volumeRegime: "Low",
    emotionTags: ["Revenge", "Tilt", "Greed"],
    notes: "Added after first stop instead of walking away.",
    ruleAdherence: 18,
    stopRespected: false,
    confidence: 8,
    stress: 10,
    sleep: 5,
    focus: 2,
    broker: "Tradovate",
    isRevenge: true,
    isFomo: false
  },
  {
    id: "TR-1019",
    ticker: "AVGO",
    assetType: "Options",
    side: "Long",
    setup: "Opening Range Breakout",
    entryPrice: 6.2,
    exitPrice: 8.1,
    positionSize: 4,
    pnl: 760,
    riskPercent: 2.3,
    plannedRisk: 500,
    actualRisk: 485,
    rMultiple: 1.57,
    durationMinutes: 58,
    date: "2026-05-04",
    time: "09:57",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined"],
    notes: "Strong relative strength and clean premarket levels.",
    ruleAdherence: 92,
    stopRespected: true,
    confidence: 6,
    stress: 3,
    sleep: 8,
    focus: 8,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1020",
    ticker: "ETH",
    assetType: "Crypto",
    side: "Short",
    setup: "Mean Reversion",
    entryPrice: 3154,
    exitPrice: 3178,
    positionSize: 14,
    pnl: -336,
    riskPercent: 2.9,
    plannedRisk: 260,
    actualRisk: 355,
    rMultiple: -1.29,
    durationMinutes: 86,
    date: "2026-05-04",
    time: "16:05",
    session: "Power Hour",
    marketRegime: "Volatile",
    volumeRegime: "Normal",
    emotionTags: ["Hesitation"],
    notes: "Late short into crypto strength.",
    ruleAdherence: 56,
    stopRespected: false,
    confidence: 5,
    stress: 6,
    sleep: 8,
    focus: 6,
    broker: "Binance",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1021",
    ticker: "META",
    assetType: "Equity",
    side: "Long",
    setup: "Trend Continuation",
    entryPrice: 482.4,
    exitPrice: 487.2,
    positionSize: 95,
    pnl: 456,
    riskPercent: 2.0,
    plannedRisk: 310,
    actualRisk: 300,
    rMultiple: 1.52,
    durationMinutes: 44,
    date: "2026-05-05",
    time: "10:41",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "Normal",
    emotionTags: ["Disciplined", "Confidence"],
    notes: "Second leg after consolidation, no chase.",
    ruleAdherence: 89,
    stopRespected: true,
    confidence: 7,
    stress: 3,
    sleep: 7,
    focus: 8,
    broker: "Interactive Brokers",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1022",
    ticker: "TSLA",
    assetType: "Options",
    side: "Long",
    setup: "Scalp",
    entryPrice: 2.4,
    exitPrice: 2.18,
    positionSize: 15,
    pnl: -330,
    riskPercent: 3.4,
    plannedRisk: 250,
    actualRisk: 345,
    rMultiple: -1.32,
    durationMinutes: 69,
    date: "2026-05-05",
    time: "12:14",
    session: "Midday",
    marketRegime: "Chop",
    volumeRegime: "Low",
    emotionTags: ["FOMO", "Impulsive"],
    notes: "Scalp turned into a hold after missing exit.",
    ruleAdherence: 41,
    stopRespected: false,
    confidence: 8,
    stress: 7,
    sleep: 7,
    focus: 4,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: true
  },
  {
    id: "TR-1023",
    ticker: "ES",
    assetType: "Futures",
    side: "Short",
    setup: "VWAP Reclaim Fail",
    entryPrice: 5261.25,
    exitPrice: 5253.75,
    positionSize: 2,
    pnl: 750,
    riskPercent: 2.4,
    plannedRisk: 470,
    actualRisk: 460,
    rMultiple: 1.63,
    durationMinutes: 33,
    date: "2026-05-06",
    time: "10:06",
    session: "Open",
    marketRegime: "Trend Down",
    volumeRegime: "High",
    emotionTags: ["Disciplined"],
    notes: "Failed reclaim gave a clean short trigger.",
    ruleAdherence: 94,
    stopRespected: true,
    confidence: 6,
    stress: 3,
    sleep: 8,
    focus: 9,
    broker: "Tradovate",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1024",
    ticker: "AMD",
    assetType: "Equity",
    side: "Long",
    setup: "Breakout",
    entryPrice: 159.2,
    exitPrice: 161.1,
    positionSize: 220,
    pnl: 418,
    riskPercent: 2.1,
    plannedRisk: 310,
    actualRisk: 310,
    rMultiple: 1.35,
    durationMinutes: 36,
    date: "2026-05-06",
    time: "15:04",
    session: "Power Hour",
    marketRegime: "Trend Up",
    volumeRegime: "Normal",
    emotionTags: ["Confidence"],
    notes: "Power hour follow-through after clean base.",
    ruleAdherence: 82,
    stopRespected: true,
    confidence: 8,
    stress: 4,
    sleep: 8,
    focus: 7,
    broker: "Webull",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1025",
    ticker: "QQQ",
    assetType: "Options",
    side: "Long",
    setup: "Opening Range Breakout",
    entryPrice: 3.2,
    exitPrice: 4.04,
    positionSize: 9,
    pnl: 756,
    riskPercent: 2.2,
    plannedRisk: 500,
    actualRisk: 490,
    rMultiple: 1.54,
    durationMinutes: 39,
    date: "2026-05-07",
    time: "09:49",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined"],
    notes: "Best structure of the week, followed scale-out plan.",
    ruleAdherence: 97,
    stopRespected: true,
    confidence: 6,
    stress: 2,
    sleep: 8,
    focus: 9,
    broker: "ThinkOrSwim",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1026",
    ticker: "COIN",
    assetType: "Options",
    side: "Short",
    setup: "Scalp",
    entryPrice: 5.1,
    exitPrice: 5.72,
    positionSize: 6,
    pnl: -372,
    riskPercent: 3.1,
    plannedRisk: 260,
    actualRisk: 380,
    rMultiple: -1.43,
    durationMinutes: 104,
    date: "2026-05-07",
    time: "12:33",
    session: "Midday",
    marketRegime: "Volatile",
    volumeRegime: "Low",
    emotionTags: ["Greed", "Tilt"],
    notes: "Tried to force continuation while market was rotating.",
    ruleAdherence: 44,
    stopRespected: false,
    confidence: 7,
    stress: 8,
    sleep: 8,
    focus: 5,
    broker: "ThinkOrSwim",
    isRevenge: true,
    isFomo: false
  },
  {
    id: "TR-1027",
    ticker: "NQ",
    assetType: "Futures",
    side: "Long",
    setup: "Trend Continuation",
    entryPrice: 18642.5,
    exitPrice: 18678.25,
    positionSize: 1,
    pnl: 715,
    riskPercent: 2.0,
    plannedRisk: 465,
    actualRisk: 455,
    rMultiple: 1.57,
    durationMinutes: 31,
    date: "2026-05-08",
    time: "10:18",
    session: "Open",
    marketRegime: "Trend Up",
    volumeRegime: "High",
    emotionTags: ["Disciplined", "Confidence"],
    notes: "Reduced size on Friday and stayed selective.",
    ruleAdherence: 93,
    stopRespected: true,
    confidence: 7,
    stress: 3,
    sleep: 7,
    focus: 8,
    broker: "Tradovate",
    isRevenge: false,
    isFomo: false
  },
  {
    id: "TR-1028",
    ticker: "SPY",
    assetType: "Options",
    side: "Long",
    setup: "Scalp",
    entryPrice: 1.7,
    exitPrice: 1.39,
    positionSize: 14,
    pnl: -434,
    riskPercent: 4.4,
    plannedRisk: 260,
    actualRisk: 445,
    rMultiple: -1.67,
    durationMinutes: 128,
    date: "2026-05-08",
    time: "13:22",
    session: "Midday",
    marketRegime: "Chop",
    volumeRegime: "Low",
    emotionTags: ["FOMO", "Tilt", "Impulsive"],
    notes: "Friday midday trade after missing the clean morning move.",
    ruleAdherence: 31,
    stopRespected: false,
    confidence: 8,
    stress: 8,
    sleep: 7,
    focus: 4,
    broker: "ThinkOrSwim",
    isRevenge: true,
    isFomo: true
  }
];

export const sampleTrades: Trade[] = buildHistoricalTrades(recentSampleTrades);

function buildHistoricalTrades(seedTrades: Trade[]): Trade[] {
  const monthStarts = [
    "2025-05-12",
    "2025-06-09",
    "2025-07-07",
    "2025-08-04",
    "2025-09-02",
    "2025-10-06",
    "2025-11-03",
    "2025-12-01",
    "2026-01-05",
    "2026-02-02",
    "2026-03-02",
    "2026-04-06"
  ];

  const historical = monthStarts.flatMap((startDate, monthIndex) => {
    const start = new Date(`${startDate}T12:00:00`);
    const monthSample = seedTrades.slice(0, 14 + (monthIndex % 4) * 2);
    const monthBias = (monthIndex - 5) * 18;

    return monthSample.map((trade, tradeIndex) => {
      const date = new Date(start);
      date.setDate(start.getDate() + Math.floor(tradeIndex / 2));
      const multiplier = 0.78 + (monthIndex % 5) * 0.08 + (tradeIndex % 3) * 0.035;
      const pnlBias = trade.pnl > 0 ? monthBias : -monthBias * 0.45;
      const pnl = Math.round(trade.pnl * multiplier + pnlBias);
      const riskDrift = monthIndex < 5 ? 0.45 : monthIndex > 8 ? -0.2 : 0;
      const ruleShift = monthIndex < 4 ? -8 : monthIndex > 8 ? 5 : 0;
      const stressShift = monthIndex < 5 ? 1 : monthIndex > 8 ? -1 : 0;

      return {
        ...trade,
        id: `HIS-${monthIndex + 1}-${tradeIndex + 1}`,
        date: date.toISOString().slice(0, 10),
        pnl,
        riskPercent: Number(Math.max(0.8, trade.riskPercent + riskDrift).toFixed(1)),
        plannedRisk: Math.round(trade.plannedRisk * multiplier),
        actualRisk: Math.round(trade.actualRisk * (multiplier + (monthIndex < 5 && trade.pnl < 0 ? 0.14 : 0))),
        rMultiple: Number((pnl / Math.max(trade.actualRisk * multiplier, 1)).toFixed(2)),
        ruleAdherence: Math.max(12, Math.min(99, trade.ruleAdherence + ruleShift)),
        stress: Math.max(1, Math.min(10, trade.stress + stressShift)),
        focus: Math.max(1, Math.min(10, trade.focus - stressShift)),
        notes:
          monthIndex < 5
            ? `${trade.notes} Historical sample: higher stress period with less consistent execution.`
            : trade.notes
      };
    });
  });

  return [...historical, ...seedTrades].sort((a, b) => `${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`));
}

export const samplePsychologyLogs: PsychologyLog[] = [
  {
    date: "2026-05-04",
    confidence: 6,
    stress: 4,
    sleep: 8,
    focus: 8,
    emotionalState: "Disciplined",
    distractions: 2,
    journal: "Good reset after Friday. Only taking A setups."
  },
  {
    date: "2026-05-05",
    confidence: 8,
    stress: 7,
    sleep: 7,
    focus: 5,
    emotionalState: "FOMO",
    distractions: 5,
    journal: "Felt behind after missing the first move."
  },
  {
    date: "2026-05-06",
    confidence: 7,
    stress: 3,
    sleep: 8,
    focus: 8,
    emotionalState: "Confidence",
    distractions: 2,
    journal: "Clear levels and calm execution."
  },
  {
    date: "2026-05-07",
    confidence: 7,
    stress: 6,
    sleep: 8,
    focus: 6,
    emotionalState: "Greed",
    distractions: 3,
    journal: "Strong start, then tried to squeeze extra trades out of chop."
  },
  {
    date: "2026-05-08",
    confidence: 8,
    stress: 8,
    sleep: 7,
    focus: 4,
    emotionalState: "Tilt",
    distractions: 4,
    journal: "Morning was good. Midday patience broke down."
  }
];

export const brokerOptions = [
  "ThinkOrSwim",
  "Tradovate",
  "Interactive Brokers",
  "Robinhood",
  "Webull",
  "Binance"
];

export const strategyOptions = [
  "Opening Range Breakout",
  "ORB",
  "VWAP Bounce",
  "VWAP Reclaim Fail",
  "Trend Continuation",
  "Breakout",
  "Mean Reversion",
  "Scalp"
];
